/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package frames;

/**
 * Class where the frontend side of the Home page is developed, as well as the
 * listeners for all the components.
 *
 * @author Juan Ignacio Campos Martí
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
        this.setExtendedState(frmHome.MAXIMIZED_BOTH);
        this.setTitle("Touristic Apartments Manager");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblIdPerson = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblLastNames = new javax.swing.JLabel();
        lblAccess = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuHome = new javax.swing.JMenu();
        mnuFile = new javax.swing.JMenu();
        mnuApartments = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenuItem();
        mnuBookings = new javax.swing.JMenu();
        mnuConsumptions = new javax.swing.JMenuItem();
        mnuCustomers = new javax.swing.JMenuItem();
        mnuPayments = new javax.swing.JMenuItem();
        mnuConsults = new javax.swing.JMenu();
        mnuConfig = new javax.swing.JMenu();
        mnuAccess = new javax.swing.JMenuItem();
        mnuTools = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();
        mnuAboutUs = new javax.swing.JMenuItem();
        mnuHelp2 = new javax.swing.JMenuItem();
        mnuOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 62, 70));

        desktop.setBackground(new java.awt.Color(57, 62, 70));

        lblIdPerson.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdPerson.setForeground(new java.awt.Color(238, 238, 238));
        lblIdPerson.setText("jLabel1");
        desktop.add(lblIdPerson);
        lblIdPerson.setBounds(50, 60, 150, 15);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(238, 238, 238));
        lblName.setText("jLabel2");
        desktop.add(lblName);
        lblName.setBounds(50, 90, 150, 15);

        lblLastNames.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastNames.setForeground(new java.awt.Color(238, 238, 238));
        lblLastNames.setText("jLabel3");
        desktop.add(lblLastNames);
        lblLastNames.setBounds(50, 120, 150, 15);

        lblAccess.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAccess.setForeground(new java.awt.Color(238, 238, 238));
        lblAccess.setText("jLabel4");
        desktop.add(lblAccess);
        lblAccess.setBounds(50, 150, 150, 15);

        menuBar.setBackground(new java.awt.Color(34, 40, 49));
        menuBar.setForeground(new java.awt.Color(34, 40, 49));

        mnuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/apartment.png"))); // NOI18N
        mnuHome.setMnemonic('f');
        mnuHome.setText("Touristic Apartments Manager");
        mnuHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuBar.add(mnuHome);

        mnuFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/carpeta.png"))); // NOI18N
        mnuFile.setMnemonic('e');
        mnuFile.setText("Archivo");
        mnuFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuApartments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuApartments.setBackground(new java.awt.Color(238, 238, 238));
        mnuApartments.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuApartments.setForeground(new java.awt.Color(57, 62, 70));
        mnuApartments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/apartamentos.png"))); // NOI18N
        mnuApartments.setMnemonic('p');
        mnuApartments.setText("Apartamentos");
        mnuApartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApartmentsActionPerformed(evt);
            }
        });
        mnuFile.add(mnuApartments);

        mnuProducts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuProducts.setBackground(new java.awt.Color(238, 238, 238));
        mnuProducts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuProducts.setForeground(new java.awt.Color(57, 62, 70));
        mnuProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/anadir-a-la-cesta.png"))); // NOI18N
        mnuProducts.setMnemonic('d');
        mnuProducts.setText("Productos");
        mnuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductsActionPerformed(evt);
            }
        });
        mnuFile.add(mnuProducts);

        menuBar.add(mnuFile);

        mnuBookings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/calendario.png"))); // NOI18N
        mnuBookings.setMnemonic('h');
        mnuBookings.setText("Reservas");
        mnuBookings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuConsumptions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuConsumptions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuConsumptions.setForeground(new java.awt.Color(57, 62, 70));
        mnuConsumptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gastos (1).png"))); // NOI18N
        mnuConsumptions.setMnemonic('c');
        mnuConsumptions.setText("Reservas y consumos");
        mnuConsumptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsumptionsActionPerformed(evt);
            }
        });
        mnuBookings.add(mnuConsumptions);

        mnuCustomers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCustomers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuCustomers.setForeground(new java.awt.Color(57, 62, 70));
        mnuCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clasificacion (1).png"))); // NOI18N
        mnuCustomers.setMnemonic('a');
        mnuCustomers.setText("Clientes");
        mnuCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustomersActionPerformed(evt);
            }
        });
        mnuBookings.add(mnuCustomers);

        mnuPayments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuPayments.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuPayments.setForeground(new java.awt.Color(57, 62, 70));
        mnuPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bolsa-de-dinero.png"))); // NOI18N
        mnuPayments.setText("Pagos");
        mnuBookings.add(mnuPayments);

        menuBar.add(mnuBookings);

        mnuConsults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/video-conferencia.png"))); // NOI18N
        mnuConsults.setText("Consultas");
        mnuConsults.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuBar.add(mnuConsults);

        mnuConfig.setForeground(new java.awt.Color(57, 62, 70));
        mnuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ajustes (1).png"))); // NOI18N
        mnuConfig.setText("Configuración");
        mnuConfig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuAccess.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAccess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuAccess.setForeground(new java.awt.Color(57, 62, 70));
        mnuAccess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/llave.png"))); // NOI18N
        mnuAccess.setText("Usuarios y Accesos");
        mnuAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAccessActionPerformed(evt);
            }
        });
        mnuConfig.add(mnuAccess);

        menuBar.add(mnuConfig);

        mnuTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/herramienta (1).png"))); // NOI18N
        mnuTools.setText("Herramientas");
        mnuTools.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuBar.add(mnuTools);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sos (1).png"))); // NOI18N
        mnuHelp.setText("Ayuda");
        mnuHelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mnuAboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAboutUs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuAboutUs.setForeground(new java.awt.Color(57, 62, 70));
        mnuAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/capitan-del-equipo (1).png"))); // NOI18N
        mnuAboutUs.setText("Acerca de");
        mnuHelp.add(mnuAboutUs);

        mnuHelp2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHelp2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mnuHelp2.setForeground(new java.awt.Color(57, 62, 70));
        mnuHelp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/faq.png"))); // NOI18N
        mnuHelp2.setText("Ayuda");
        mnuHelp.add(mnuHelp2);

        menuBar.add(mnuHelp);

        mnuOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cerrar-sesion (3).png"))); // NOI18N
        mnuOut.setText("Salir");
        mnuOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mnuOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuOutMouseClicked(evt);
            }
        });
        menuBar.add(mnuOut);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuConsumptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsumptionsActionPerformed
        frmBooking frmBooking = new frmBooking();
        desktop.add(frmBooking);
        frmBooking.toFront();
        frmBooking.setVisible(true);
        frmBooking.txtIdEmployee.setText(lblIdPerson.getText());
        frmBooking.txtEmployeeName.setText(lblName.getText() + " " 
                + lblLastNames.getText());
        frmBooking.idUser = Integer.parseInt(lblIdPerson.getText());
        
    }//GEN-LAST:event_mnuConsumptionsActionPerformed

    /**
     * Procedure that displays the frmApartment once the "Apartamentos" menu
     * item is clicked.
     *
     * @see frmApartment
     * @param evt A click on the menu item "Apartamentos".
     */
    private void mnuApartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApartmentsActionPerformed
        frmApartment form = new frmApartment();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuApartmentsActionPerformed

    /**
     * Procedure that displays the frmProduct once the "Productos" menu
     * item is clicked.
     *
     * @see frmProduct
     * @param evt A click on the menu item "Productos".
     */
    private void mnuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductsActionPerformed
        frmProduct form = new frmProduct();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuProductsActionPerformed

    /**
     * Procedure that displays the frmCustomer once the "Clientes" menu 
     * item is clicked.
     * 
     * @see frmCustomer
     * @param evt A click on the menu item "Clientes".
     */
    private void mnuCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustomersActionPerformed
        frmCustomer form = new frmCustomer();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuCustomersActionPerformed

        /**
     * Procedure that displays the frmEmployee once the "Usuarios y accesos" menu 
     * item is clicked.
     * 
     * @see frmEmployee
     * @param evt A click on the menu item "Usuarios y accesos".
     */
    private void mnuAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAccessActionPerformed
        frmEmployee form = new frmEmployee();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mnuAccessActionPerformed

    /**
     * Procedure that closes the app once the "Salir" menu item is clicked.
     * @param evt A click on the "Salir" menu item.
     */
    private void mnuOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuOutMouseClicked
        this.dispose();
    }//GEN-LAST:event_mnuOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    public static javax.swing.JLabel lblAccess;
    public static javax.swing.JLabel lblIdPerson;
    public static javax.swing.JLabel lblLastNames;
    public static javax.swing.JLabel lblName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAboutUs;
    private javax.swing.JMenuItem mnuAccess;
    private javax.swing.JMenuItem mnuApartments;
    private javax.swing.JMenu mnuBookings;
    public static javax.swing.JMenu mnuConfig;
    private javax.swing.JMenu mnuConsults;
    private javax.swing.JMenuItem mnuConsumptions;
    private javax.swing.JMenuItem mnuCustomers;
    public static javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHelp2;
    private javax.swing.JMenu mnuHome;
    private javax.swing.JMenu mnuOut;
    private javax.swing.JMenuItem mnuPayments;
    private javax.swing.JMenuItem mnuProducts;
    private javax.swing.JMenu mnuTools;
    // End of variables declaration//GEN-END:variables

}
